#!/usr/bin/env bash
# Get the records type
dig_fun () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    dig_fun "$2.$1" "$2"
else
    dig_fun "www.$1" "www"
    dig_fun "lb-01.$1" "lb-01"
    dig_fun "web-01.$1" "web-01"
    dig_fun "web-02.$1" "web-02"
fi
