#!/usr/bin/env bash
# reidrection
apt update -y
apt install -y nginx
echo "Hello World!" >  /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
