#!/usr/bin/env bash
# reidrection
apt update -y
apt install -y nginx
echo "Hello World!" >  /var/www/html/index.nginx-debian.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
