#!/usr/bin/env bash
# reidrection
apt update -y
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
sed -i '/listen 80 default_server/a redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
service nginx restart
