#!/usr/bin/env bash
# advance 1
terminator() {
rm /var/run/myscript.pid
exit
}

echo "$$" > /var/run/myscript.pid

while((1))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
